// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/colour-upload/Accessibility.tsx": () => import("../components/mockups/colour-upload/Accessibility.tsx"),
  "./components/mockups/colour-upload/Affordance.tsx": () => import("../components/mockups/colour-upload/Affordance.tsx"),
  "./components/mockups/colour-upload/Hierarchy.tsx": () => import("../components/mockups/colour-upload/Hierarchy.tsx")
};
